config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "users#index"

  devise_scope :user do get '/users/sign_out' => 'devise/sessions#destroy' end

    resources :users, only: [:index, :show]  do
      resources :posts, only: [:index, :show, :new, :create, :destroy] do
        resources :comments, only: [:new, :create, :destroy]
        resources :likes, only: [:create]
      end
    end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.role == 'admin'
      can :manage, :all
    else
      can %i[read create], :all
      can %i[update destroy], Post, author_id: user.id
      can %i[update destroy], Comment, author_id: user.id

    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_save :update_comment_counter

  private

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_post_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_five_comments
    comments.order(updated_at: :desc).last(5)
  end

  private

  def update_post_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  validates :name, presence: true, allow_blank: false
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_three_posts
    posts.order(updated_at: :desc).last(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :bio, :photo, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :photo, :email, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def new
    @comment = Comment.new
    respond_to do |format|
      format.html { render :new, locals: { comment: @comment } }
    end
  end

  def comment_params
    params
      .require(:comment)
      .permit(:text)
      .merge(author: current_user, post_id: params.require(:post_id))
  end

  def create
    @comment = Comment.new(comment_params)
    respond_to do |format|
      format.html do
        if @comment.save
          flash[:success] = 'Comment saved successfully'
          redirect_to user_post_path(current_user, @comment.post)
        else
          flash.now[:error] = 'Error: Comment could not be saved'
          redirect_to new_post_comment_path(current_user)
        end
      end
    end
  end

  def destroy
    @post = Post.includes(:comments).find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    @post.comments_counter -= 1
    @post.save

    respond_to do |format|
      format.html { redirect_to(user_posts_url) }
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def like_params
    params
      .require(:like)
      .permit(:post_id)
      .merge(author: current_user)
  end

  def create
    @like = Like.new(like_params)
    respond_to do |format|
      format.html do
        if @like.save
          redirect_to user_post_path(current_user, @like.post)
        else
          flash.now[:error] = 'Error: Like could not be saved'
          redirect_to user_post_path(current_user)
        end
      end
    end
  end

  helper_method :create
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: @post } }
    end
  end

  def post_params
    params
      .require(:post)
      .permit(:title, :text)
      .merge(author: current_user, comments_counter: 0, likes_counter: 0)
  end

  def create
    @post = Post.new(post_params)
    respond_to do |format|
      format.html do
        if @post.save
          flash[:success] = 'Post saved successfully'
          redirect_to user_post_path(current_user, @post)
        else
          flash.now[:error] = 'Error: Post could not be saved'
          redirect_to new_user_post_path(current_user)
        end
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    @user = current_user
    @user.posts_counter -= 1
    @user.save

    respond_to do |format|
      format.html { redirect_to(user_posts_url) }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Author:</strong>
    <%= comment.author_id %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= comment.post_id %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= comment.text %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :author_id, style: "display: block" %>
    <%= form.text_field :author_id %>
  </div>

  <div>
    <%= form.label :post_id, style: "display: block" %>
    <%= form.text_field :post_id %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h2 class="descriptive-title">New Comment</h2>
<%= form_with model: comment, url: user_post_comments_url, method: :post do |f| %>
  <div class="form-card">
  <div>
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  
  <div>
  <%= f.submit "Add Comment" %>
  </div>
  </div>
  <% end %>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
<%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_header.html.erb
<header>
<nav class="nav-bar">
     <% if user_signed_in? %>
    <li><%= link_to 'Home', users_path%></li>
    <li><%= link_to 'Sign Out', destroy_user_session_path%></li>
    <li><%= link_to 'Edit Profile', edit_user_registration_path%></li>
    <% else %>
 
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
    <li><%= link_to 'Log In', new_user_session_path, method: :delete %></li>
    <% end %>
   
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'style.css' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
 <%= render 'layouts/header' %>

    <%= yield %>
  </body>
</html>

app/views/likes/_form.html.erb
<%= form_with model: @like, local: true do |f| %>
<%= f.submit "Like" %>
<% end %>

app/views/likes/_like.html.erb
<div id="<%= dom_id like %>">
  <p>
    <strong>Author:</strong>
    <%= like.author_id %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= like.post_id %>
  </p>

</div>

app/views/likes/edit.html.erb
<h1>Editing like</h1>

<%= render "form", like: @like %>

<br>

<div>
  <%= link_to "Show this like", @like %> |
  <%= link_to "Back to likes", likes_path %>
</div>

app/views/likes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Likes</h1>

<div id="likes">
  <% @likes.each do |like| %>
    <%= render like %>
    <p>
      <%= link_to "Show this like", like %>
    </p>
  <% end %>
</div>

<%= link_to "New like", new_like_path %>

app/views/likes/new.html.erb
<h1>New like</h1>

<%= render "form", like: @like %>

<br>

<div>
  <%= link_to "Back to likes", likes_path %>
</div>

app/views/likes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @like %>

<div>
  <%= link_to "Edit this like", edit_like_path(@like) %> |
  <%= link_to "Back to likes", likes_path %>

  <%= button_to "Destroy this like", @like, method: :delete %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :author_id, style: "display: block" %>
    <%= form.text_field :author_id %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_area :text %>
  </div>

  <div>
    <%= form.label :comment_counter, style: "display: block" %>
    <%= form.number_field :comment_counter %>
  </div>

  <div>
    <%= form.label :likes_counter, style: "display: block" %>
    <%= form.number_field :likes_counter %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Author:</strong>
    <%= post.author_id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= post.text %>
  </p>

  <p>
    <strong>Comment counter:</strong>
    <%= post.comment_counter %>
  </p>

  <p>
    <strong>Likes counter:</strong>
    <%= post.likes_counter %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<h2 class="descriptive-title">Here is a list of posts for a given user<h2>

<%= render "users/user_card" %>
<% @posts.each do |post| %>
    <div class="post-card">
    <br>
<%= link_to  post.title, user_post_path(@user, post)  %>

<br>
<p><%= post.text %></p>
<span class="counter-card">
<span>Comments: </span><%= post.comments_counter %>
<span>, Likes: </span><%= post.likes_counter %>
</span>
<br>
</div>
<div class="comment-card">
 <% post.comments.includes(:author).order(updated_at: :desc).last(5).each do |comment| %>
    
    <span><%= comment.author.name %></span>

    <span><%= comment.text%></span>
    <br>
    
    <% end %>
    </div>
    <% end %>
    <%= link_to  "Create new Post", new_user_post_path(@user)  %>

    <button>Pagination</button>

app/views/posts/new.html.erb
<h1 class="descriptive-title">New Post</h1>
    <%= form_with model: @post, url: user_posts_path, method: :post,  local: true, scope: :post  do |f| %>
      <div class="form-card">

    <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  
  <div>
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>

<div>
  <%= f.submit "Add Post" %>
</div>
</div>
<% end %>

app/views/posts/show.html.erb
<h1 class="descriptive-title">Here is a specific post for a given user<h1>
<div class="post-card">
<span><%= @post.title  %></span><span> by </span><span><%= @post.author.name  %></span>
<br>
<span class="counter-card">
<span>Comments: <%= @post.comments_counter %></span>
<span>, Likes: <%= @post.likes_counter %></span>
</span>
<br>
<p><%= @post.text %></p>
</div>
<div class="comment-card">
<% @post.comments.includes(:author).each do |comment| %>
    <span><%= comment.author.name %>:</span>
    <span><%= comment.text%></span>
    <br>
    <% if can? :destroy, comment%>
    <%= button_to 'delete', user_post_comment_path(post_id: @post.id ,id: comment.id), :method => :delete, data: { confirm: 'Are you sure?' } %>
    <%end%>
    
<% end %>
</div>
<div class="like-div">
<button><%= link_to  "Create new Comment", new_user_post_comment_path(@post.author, @post)  %></button>
<%= render partial: 'likes/form' %>
<%if can? :destroy, @post %>
<%=button_to 'Delete post', user_post_path(post_id: @post.id), :method => :delete, data: { confirm: 'Are you sure?' } %>
<%end%>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.text_field :photo %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_field :bio %>
  </div>

  <div>
    <%= form.label :posts_counter, style: "display: block" %>
    <%= form.number_field :posts_counter %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Photo:</strong>
    <%= user.photo %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= user.bio %>
  </p>

  <p>
    <strong>Posts counter:</strong>
    <%= user.posts_counter %>
  </p>

</div>

app/views/users/_user_card.html.erb
<div class="user-card">
<%= image_tag(@user.photo, :size => "260x180") %>
<div class="user-info">
<%= @user.name %>
<span class="counter-card">Numeber of posts: <%= @user.posts_counter %></span>
</div>
<br>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<h1 class="descriptive-title">Here is the list of users</h1>
 <% @users.each do |user| %>
    <div class= "user-card">
    
    <%= image_tag(user.photo, :size => "260x180") %>
<div class= "user-info">

    <%= link_to  user.name, user_path(user.id)  %>

    <span class="counter-card">Number of posts: <%= user.posts_counter %></span>
</div>
</div>

<br>
     <% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<h1 class="descriptive-title">Here is a specific user<h1>

<%= render "user_card" %>
<div class="bio-card">
<h2>Bio<h2>
<p><%= @user.bio %></p>
</div>

<% @user.recent_three_posts.each do |post| %>
    <div class="post-card">
    <br>
    <%= link_to  post.title, user_post_path(@user, post)  %>

<p><%= post.text %></p>
<span class="counter-card">
<span>Comments: <%= post.comments_counter %></span>

<span>, Likes: <%= post.likes_counter %></span>
</span>
</div>
<% end %>
<%= link_to  "Create new Post", new_user_post_path(@user)  %>

<button><%= link_to  "See all posts", user_posts_path(@user)  %></button>